#!/usr/bin/env python3
"""
Extract Phase-2 hodoscope-QC run lists from rsidis_runlist_phaseII.dat.

Typical use from RP_Scripts/calibration_check_v1:

  python3 macros/phase2_hodo_runlists.py --spec all
  python3 macros/phase2_hodo_runlists.py --spec coin --format root
  python3 macros/phase2_hodo_runlists.py --spec all --write-command-file

The script does not modify the ROOT macro. It only prints run lists/commands
or writes a local command text file that can be pasted into cdaq.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable


DEFAULT_ROOTDIR = "/net/cdaq/cdaql3data/cdaq/hallc-online-rsidis2025/ROOTfiles"


def default_runlist_candidates() -> list[Path]:
    home = Path.home()
    return [
        Path("../JLab_upstream_forks/hallc_replay_rsidis/AUX_FILES/rsidis_runlist_phaseII.dat"),
        Path("../../JLab_upstream_forks/hallc_replay_rsidis/AUX_FILES/rsidis_runlist_phaseII.dat"),
        home / "Documents/JLab/JLab_upstream_forks/hallc_replay_rsidis/AUX_FILES/rsidis_runlist_phaseII.dat",
    ]


def find_default_runlist() -> Path:
    for candidate in default_runlist_candidates():
        if candidate.expanduser().exists():
            return candidate.expanduser()
    tried = "\n  ".join(str(path) for path in default_runlist_candidates())
    raise FileNotFoundError(
        "Could not find rsidis_runlist_phaseII.dat automatically. Tried:\n"
        f"  {tried}\n"
        "Pass it explicitly with --runlist."
    )


def parse_runlist(path: Path) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("!"):
            continue

        fields = line.split()
        if len(fields) < 12 or not fields[0].isdigit():
            continue

        rows.append(
            {
                "run": fields[0],
                "date": fields[1],
                "start_time": fields[2],
                "ebeam": fields[3],
                "ibeam": fields[4],
                "target": fields[5],
                "hms_p": fields[6],
                "hms_th": fields[7],
                "shms_p": fields[8],
                "shms_th": fields[9],
                "prescales": fields[10],
                "run_type": fields[11],
                "comment": " ".join(fields[12:]),
            }
        )
    return rows


def runs_for_spec(rows: Iterable[dict[str, str]], spec: str) -> list[int]:
    spec_to_types = {
        "coin": {"PI-SIDIS", "PI+SIDIS"},
        "hms": {"HMSDIS"},
        "shms_electron": {"SHMSDIS"},
    }
    wanted = spec_to_types[spec]
    return [int(row["run"]) for row in rows if row["run_type"] in wanted]


def compact_runs(runs: Iterable[int]) -> str:
    ordered = sorted(set(runs))
    if not ordered:
        return ""

    ranges: list[str] = []
    start = previous = ordered[0]
    for run in ordered[1:]:
        if run == previous + 1:
            previous = run
            continue
        ranges.append(f"{start}" if start == previous else f"{start}-{previous}")
        start = previous = run
    ranges.append(f"{start}" if start == previous else f"{start}-{previous}")
    return ",".join(ranges)


def root_command(spec: str, run_string: str, rootdir: str, output_mode: str) -> str:
    return (
        "root -l -b -q "
        f"'macros/hodo_calib_qc_batch_phase2.C+(\"{spec}\","
        f"\"{rootdir}\",\"{run_string}\",\"{output_mode}\")'"
    )


def cdaq_command(spec: str, run_string: str, rootdir: str, output_mode: str) -> str:
    return "\n".join(
        [
            'builddir="/tmp/hodo_phase2_rparvez"',
            'mkdir -p "$builddir"',
            "",
            "root -l -b -q \\",
            '  -e "gSystem->SetBuildDir(\\"$builddir\\", kTRUE);" \\',
            (
                "  'macros/hodo_calib_qc_batch_phase2.C+("
                f'"{spec}","{rootdir}","{run_string}","{output_mode}")\''
            ),
        ]
    )


def command_file_text(
    runlist: Path,
    rows: list[dict[str, str]],
    specs: list[str],
    rootdir: str,
    output_mode: str,
) -> str:
    lines: list[str] = [
        "# Phase-2 hodoscope QC commands",
        "# Generated by calibration_check_v1/macros/phase2_hodo_runlists.py",
        f"# Runlist: {runlist}",
        f"# ROOT directory: {rootdir}",
        f"# Output mode: {output_mode}",
        "#",
        "# Regenerate this file whenever rsidis_runlist_phaseII.dat changes.",
        "",
    ]
    for spec in specs:
        runs = runs_for_spec(rows, spec)
        run_string = compact_runs(runs)
        lines.extend(
            [
                f"===== {spec} =====",
                f"count: {len(runs)}",
                f"runs: {run_string}",
                "",
                cdaq_command(spec, run_string, rootdir, output_mode),
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Phase-2 hodoscope-QC run lists from rsidis_runlist_phaseII.dat."
    )
    parser.add_argument(
        "--runlist",
        type=Path,
        default=None,
        help="Path to rsidis_runlist_phaseII.dat. If omitted, common local locations are tried.",
    )
    parser.add_argument(
        "--spec",
        choices=["coin", "hms", "shms_electron", "all"],
        default="all",
        help="Run category to print. 'all' means coin, hms, and shms_electron.",
    )
    parser.add_argument(
        "--format",
        choices=["summary", "runs", "root", "cdaq"],
        default="summary",
        help="summary prints counts and compact run lists; runs prints only compact run lists; root prints ROOT commands; cdaq prints low-priority cdaq command blocks.",
    )
    parser.add_argument(
        "--rootdir",
        default=DEFAULT_ROOTDIR,
        help="ROOT-file directory to include in --format root output.",
    )
    parser.add_argument(
        "--output-mode",
        default="pdf,csv",
        help='Output mode string for ROOT calls, e.g. "pdf,csv" or "pdf,csv,png".',
    )
    parser.add_argument(
        "--write-command-file",
        action="store_true",
        help="Write cdaq-ready command blocks to macros/phase2_hodo_root_commands.txt.",
    )
    parser.add_argument(
        "--command-file",
        type=Path,
        default=Path(__file__).with_name("phase2_hodo_root_commands.txt"),
        help="Path used with --write-command-file.",
    )
    args = parser.parse_args()

    runlist = args.runlist.expanduser() if args.runlist else find_default_runlist()
    rows = parse_runlist(runlist)
    specs = ["coin", "hms", "shms_electron"] if args.spec == "all" else [args.spec]

    if args.write_command_file:
        output = args.command_file.expanduser()
        output.write_text(
            command_file_text(runlist, rows, specs, args.rootdir, args.output_mode)
        )
        print(f"Wrote command file: {output}")

    if args.format == "summary":
        print(f"Runlist: {runlist}")
        print(f"Parsed rows: {len(rows)}")

    for spec in specs:
        runs = runs_for_spec(rows, spec)
        run_string = compact_runs(runs)
        if args.format == "summary":
            print(f"\n[{spec}]")
            print(f"count: {len(runs)}")
            print(f"runs: {run_string}")
            print(root_command(spec, run_string, args.rootdir, args.output_mode))
        elif args.format == "runs":
            print(run_string)
        elif args.format == "root":
            print(root_command(spec, run_string, args.rootdir, args.output_mode))
        else:
            print(cdaq_command(spec, run_string, args.rootdir, args.output_mode))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
