#!/usr/bin/env python3
"""
make_groups_z_overlay.py

Create a z-overlay group file for PlotCoinXsec in "overlay mode".

It scans a v5 settings tree generated by generate_settings_tree_v5.py and writes a group file:

  groups/<pass>/<run_type>/<target>/<x>/<q2>/<tpq_label>/grp_<TARGET>_zOv_<x>_Q2<q2>_tpq<tpq_label>.list

Each line in the group file is:
  <label> <relative/path/to/manifest.json>

Example:
  python3 tools/make_groups_z_overlay.py \
    --settings-root settings \
    --groups-root   groups \
    --pass          pass4 \
    --run-type      "pi+sidis" \
    --target        LH2 \
    --x             x0p25 \
    --q2            q23p3 \
    --tpq           2.0 \
    --z-dirs        z0p36 z0p5 z0p67 \
    --require-substr hmsPneg1p531 hmsTh29p045 shmsTh7p865

Notes:
- If multiple setting directories match a given z-dir, you MUST disambiguate using --require-substr.
- For labeling, z0p5 is rendered as z0p50 in the output group file.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import List, Dict


def _format_dir_value(prefix: str, val: float, digits: int = 3) -> str:
    # Mirror generate_settings_tree_v5 formatting (strip trailing zeros; '.' -> 'p'; '-' -> 'neg')
    s = f"{val:.{digits}f}".rstrip("0").rstrip(".")
    s = s.replace("-", "neg").replace(".", "p")
    return f"{prefix}{s}"


def _tpq_label(val: float) -> str:
    # User-facing label in group directory + filename (tpq2p0 for 2.0)
    # Keep one decimal place for clarity.
    s = f"{val:.1f}".replace(".", "p").replace("-", "neg")
    return f"tpq{s}"


def _z_label(z_dir: str) -> str:
    # z0p5 -> z0p50 (for legend readability); otherwise unchanged
    if z_dir == "z0p5":
        return "z0p50"
    return z_dir


def _find_manifest_for_z(settings_root: Path,
                         pass_key: str,
                         run_type: str,
                         target: str,
                         z_dir: str,
                         x_dir: str,
                         q2_dir: str,
                         thpq_dir: str,
                         require_substr: List[str]) -> Path:
    base = settings_root / pass_key / run_type / target / z_dir / x_dir / q2_dir
    if not base.is_dir():
        raise FileNotFoundError(f"Missing expected directory: {base}")

    # Candidates are setting_id directories under base that contain thpq_dir token.
    candidates = []
    for d in sorted(base.iterdir()):
        if not d.is_dir():
            continue
        if thpq_dir not in d.name:
            continue
        if require_substr and not all(s in d.name for s in require_substr):
            continue
        mp = d / "manifest.json"
        if mp.exists():
            candidates.append(mp)

    if len(candidates) == 0:
        msg = f"No manifest.json found for z={z_dir} under {base} (thpq_dir={thpq_dir})"
        if require_substr:
            msg += f" with require_substr={require_substr}"
        raise FileNotFoundError(msg)

    if len(candidates) > 1:
        # Provide a readable list to help user pick substrings.
        lines = "\n".join(f"  - {c.parent.name}" for c in candidates[:50])
        raise RuntimeError(
            f"Ambiguous match for z={z_dir} under {base} (found {len(candidates)} candidates).\n"
            f"Add --require-substr tokens to uniquely select one setting directory.\n"
            f"Candidates:\n{lines}\n"
        )

    return candidates[0]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--settings-root", default="settings", help="Root of settings tree (default: settings)")
    ap.add_argument("--groups-root", default="groups", help="Root of groups tree (default: groups)")
    ap.add_argument("--pass", dest="pass_key", required=True, help="pass key (e.g., pass4)")
    ap.add_argument("--run-type", required=True, help="run type dir (e.g., pi+sidis)")
    ap.add_argument("--target", required=True, help="Target dir (e.g., LH2)")
    ap.add_argument("--x", dest="x_dir", required=True, help="x dir (e.g., x0p25)")
    ap.add_argument("--q2", dest="q2_dir", required=True, help="q2 dir (e.g., q23p3)")
    ap.add_argument("--tpq", type=float, required=True, help="theta_pq value used for naming (e.g., 2.0)")
    ap.add_argument("--z-dirs", nargs="+", default=["z0p36", "z0p5", "z0p67"], help="z dirs to include")
    ap.add_argument("--require-substr", nargs="*", default=[],
                    help="One or more substrings that MUST appear in the setting_id directory name (to disambiguate).")
    ap.add_argument("--overwrite", action="store_true", help="Overwrite existing group file if present")
    args = ap.parse_args()

    settings_root = Path(args.settings_root).expanduser().resolve()
    groups_root = Path(args.groups_root).expanduser().resolve()

    target_dir = args.target.upper()
    thpq_dir = _format_dir_value("thpq", args.tpq, digits=3)  # e.g., thpq2
    tpq_label = _tpq_label(args.tpq)                          # e.g., tpq2p0

    group_dir = groups_root / args.pass_key / args.run_type / target_dir / args.x_dir / args.q2_dir / tpq_label
    group_dir.mkdir(parents=True, exist_ok=True)

    group_file = group_dir / f"grp_{target_dir}_zOv_{args.x_dir}_Q{args.q2_dir[1:]}_{tpq_label}.list"
    if group_file.exists() and not args.overwrite:
        raise SystemExit(f"Group file exists (use --overwrite): {group_file}")

    lines = []
    lines.append(f"# z-overlay group for {args.run_type}, {args.pass_key}, {target_dir}")
    lines.append(f"# nominal: x={args.x_dir} Q2={args.q2_dir} theta_pq={args.tpq:.1f}")
    lines.append("# format: <label> <path-to-manifest.json>")
    lines.append("")

    for z_dir in args.z_dirs:
        mp = _find_manifest_for_z(
            settings_root=settings_root,
            pass_key=args.pass_key,
            run_type=args.run_type,
            target=target_dir,
            z_dir=z_dir,
            x_dir=args.x_dir,
            q2_dir=args.q2_dir,
            thpq_dir=thpq_dir,
            require_substr=args.require_substr,
        )
        rel = os.path.relpath(mp, start=group_dir)
        lines.append(f"{_z_label(z_dir):<6}  {rel}")

    group_file.write_text("\n".join(lines) + "\n")
    print(f"Wrote group file: {group_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
