#!/bin/tcsh -f
# ------------------------------------------------------------
# generator_coin_minus_positron_runs.tcsh
#
# Usage (run from calibration_check_v1/):
#   tcsh tools/generator_coin_minus_positron_runs.tcsh
#
# What it does:
#   - Reads:  bigtable/rsidis_bigtable_pass0p1.csv
#   - Writes: include/runs_vec_coin_minus_positron.hh
#
# Selection:
#   - run_type == PI+SIDIS or PI-SIDIS
#   - hms_p < 0  (exclude positron runs with hms_p > 0)
#
# Notes:
#   Assumes CSV columns (as in pass0p1 bigtable):
#     col 1 = runnum
#     col 4 = hms_p
#     col 8 = run_type
# ------------------------------------------------------------

set in_csv  = "bigtable/rsidis_bigtable_pass0p1.csv"
set out_hh  = "include/runs_vec_coin_minus_positron.hh"
set tmp_runs = "/tmp/coin_minus_positron_runs_$$.txt"

# Basic checks
if ( ! -e "$in_csv" ) then
  echo "[ERROR] Input CSV not found: $in_csv"
  echo "        Run this from calibration_check_v1/ or edit in_csv path."
  exit 1
endif

# Extract run numbers, filter, sort unique
# - NR>1 skips header
# - $8 is run_type, $4 is hms_p, $1 is runnum
awk -F, 'NR>1 && ($8=="PI+SIDIS" || $8=="PI-SIDIS") && ($4+0)<0 {print $1}' "$in_csv" \
  | sort -n -u >! "$tmp_runs"

if ( ! -s "$tmp_runs" ) then
  echo "[ERROR] No runs selected. Check column indices or CSV content."
  echo "        Expected: col1=run, col4=hms_p, col8=run_type."
  /bin/rm -f "$tmp_runs"
  exit 2
endif

# Write header file
set n = `wc -l < "$tmp_runs"`
echo "[INFO] Selected $n runs. Writing: $out_hh"

cat >! "$out_hh" << EOF
#pragma once
#include <vector>

// Auto-generated by: tools/generator_coin_minus_positron_runs.tcsh
// Input CSV: ${in_csv}
//
// Selection:
//   run_type == PI+SIDIS or PI-SIDIS
//   hms_p < 0   (exclude positron runs)

static const std::vector<int> COINRuns = {
EOF

awk '{ printf("  %s,\n", $1) }' "$tmp_runs" >> "$out_hh"

cat >> "$out_hh" << EOF
};
EOF

/bin/rm -f "$tmp_runs"

echo "[DONE] Wrote: $out_hh"
exit 0
