#!/bin/tcsh -f
# ------------------------------------------------------------
# generator_hmsdis.tcsh
#
# Run from calibration_check_v1/:
#   tcsh tools/generator_hmsdis.tcsh
#
# Reads:
#   bigtable/rsidis_bigtable_pass0p1.csv
#
# Writes:
#   include/runs_vec_hmsdis.hh
#
# Selection:
#   run_type (col 8) == HMSDIS
# Output vector name:
#   HMSRuns
# ------------------------------------------------------------

set in_csv  = "bigtable/rsidis_bigtable_pass0p1.csv"
set out_hh  = "include/runs_vec_hmsdis.hh"
set tmp_runs = "/tmp/hmsdis_runs_$$.txt"

echo "[INFO] PWD: $cwd"
echo "[INFO] Input:  $in_csv"
echo "[INFO] Output: $out_hh"

if ( ! -e "$in_csv" ) then
  echo "[ERROR] Input CSV not found: $in_csv"
  exit 1
endif

if ( ! -d "include" ) then
  mkdir -p include
endif

# Extract runs (col1) where run_type (col8) == HMSDIS; skip header line
# Then sort unique numerically
awk -F, 'NR>1 && $8=="HMSDIS" {print $1}' "$in_csv" | sort -n -u >! "$tmp_runs"

if ( ! -s "$tmp_runs" ) then
  echo "[ERROR] No HMSDIS runs selected (run_type==HMSDIS)."
  /bin/rm -f "$tmp_runs"
  exit 2
endif

# Write header file
cat >! "$out_hh" << EOF
#pragma once
#include <vector>

// Auto-generated by: tools/generator_hmsdis.tcsh
// Input CSV: bigtable/rsidis_bigtable_pass0p1.csv
// Selection: run_type == HMSDIS

static const std::vector<int> HMSRuns = {
EOF

awk '{ printf("  %s,\n", $1) }' "$tmp_runs" >> "$out_hh"

cat >> "$out_hh" << EOF
};
EOF

/bin/rm -f "$tmp_runs"

echo "[DONE] Wrote: $out_hh"
ls -l "$out_hh"
exit 0
